赤外線リモコン学習#1
libertyfish-co/ruby-hw pull request #16
Opened 2021-01-15 16:30 UTC by TakatoshiNakadate

赤外線リモコン学習のコードと、配線図です。

レビューをお願いします。

2021-06-19 05:58 UTC, soruma commented
@TakatoshiNakadate 
タクトスイッチの全体的な使い方なのですが、上側のボタンが押したら繋がる端子が逆ではないでしょうか?
この図のままだと、常時電流が流れた状態になると思います。

左下から入った電流は左上に常に出力され、ボタンが押されると右上にも出力されるはずです。

![](https://deviceplus.jp/wp-content/uploads/2019/09/21.png)

2021-06-19 09:39 UTC, TakatoshiNakadate commented
お！すみません。実装では接続しないように配線していたのですが、清書するときに結線してしまったようです。
![IMG_0645](https://user-images.githubusercontent.com/30851875/122638175-aeb89d00-d12d-11eb-9e8b-26b2dde12e03.JPG)

2021-06-19 12:20 UTC, TakatoshiNakadate commented
画像差し替えました。

2021-07-11 14:00 UTC, soruma requested changes

2021-07-12 14:15 UTC, TakatoshiNakadate commented on ir_remote_controller.md
> +```ruby:ir_receiver_and_ir_transmitter.rb
修正しました:end:

2021-07-12 14:16 UTC, TakatoshiNakadate commented on ir_remote_controller.md
> +W = V * A = (5-1.35) * 0.0474 = 0.173W
修正しました:end:

2021-07-12 14:16 UTC, TakatoshiNakadate commented on ir_remote_controller.md
> +    send_button = PiPiper::Pin.new :pin => 24
修正しました:end:

2021-07-16 11:19 UTC, soruma approved these changes

2021-07-16 11:19 UTC, merged